
Lars1{
  Angle 8  ; angle increment/decrement is 45
  axiom [F]++[F]++[F]++F
  F=F[+F][-F]
  }

Lars2{
  Angle 8  ; angle increment/decrement is 45
  axiom +[F]++[F]++[F]++F
  F=F[+F][-F]
  }

LarsColor1{
  Angle 8  ; angle increment/decrement is 45
  axiom C1[F]++[F]++[F]++F
  F=F<1[+F<1][-F<1]
  }

LarsColor2{
  Angle 8  ; angle increment/decrement is 45
  axiom C1+[F]++[F]++[F]++F
  F=F<1[+F<1][-F<1]
  }

