
Newton_poly { ; Tim Wegner - use float=yes
   ; fractal generated by Newton formula z^3 - 3z
   z = pixel, z2 = z*z, z3 = z*z2:
   z = (2*z3) / (3*z2 - 3);
   z2 = z*z;
   z3 = z*z2,
  .004 <= |z3 - 3*z|
  }

